/// Copyright 2011-2017 - asm128
#include "nwol_enum.h"

#ifndef __DATAUSAGE_H__928364092634829374234__
#define __DATAUSAGE_H__928364092634829374234__

namespace nwol
{
	// This is to let the api know how to deal with the data
	GDEFINE_ENUM_TYPE(GDATA_USAGE, uint32_t);
#define GDATA_TYPE_RESOURCEUSAGE	GDATA_TYPE_UINT32
	
	// 
	//GDEFINE_ENUM_VALUE(GDATA_USAGE, 0		, SUBSYS_NONE		);
	GDEFINE_ENUM_VALUE(GDATA_USAGE	, SUBSYS_CORE		, 1<<28);
	GDEFINE_ENUM_VALUE(GDATA_USAGE	, SUBSYS_VIDEO		, 1<<29);
	GDEFINE_ENUM_VALUE(GDATA_USAGE	, SUBSYS_AUDIO		, 1<<30);
	GDEFINE_ENUM_VALUE(GDATA_USAGE	, SUBSYS_PHYSICS	, 1<<31);

	// Base usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_UNKNOWN				, 0											);
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BINARY				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 0  )	);	// 0x10000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TEXT				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 1  )	);	// 0x10000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_POINTER				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 2  )	);	// 0x10000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DATATYPE			, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 3  )	);	// 0x10000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BEGIN				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 4  )	);	// 0x10000010;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_END					, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 5  )	);	// 0x10000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_USAGE				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 6  )	);	// 0x10000040;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 7  )	);	// 0x10000080;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_POD					, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 8  )	);	// 0x10000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_CLASS				, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 9  )	);	// 0x10000200;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_SCANCODE			, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 10 )	);	// 0x10000400;

	// Derived base usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_SCALAR				, GUSAGE_NUMERIC			| ( 1 << 11 )	);	// 0x10000800;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VECTOR				, GUSAGE_NUMERIC			| ( 1 << 12 )	);	// 0x10001000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BOOLEAN				, GUSAGE_NUMERIC			| ( 1 << 13 )	);	// 0x10002000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_RANGE				, GUSAGE_NUMERIC			| ( 1 << 14 )	);	// 0x10004000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_MAP					, GUSAGE_NUMERIC			| ( 1 << 15 )	);	// 0x10004000;

	// Video usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_INDEX				, GDATA_USAGE_SUBSYS_VIDEO	|  1			);	// 0x20000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VERTEX				, GDATA_USAGE_SUBSYS_VIDEO	|  2			);	// 0x20000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NORMAL				, GDATA_USAGE_SUBSYS_VIDEO	|  3			);	// 0x20000003;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TEXCOORD			, GDATA_USAGE_SUBSYS_VIDEO	|  4			);	// 0x20000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VERTEXCOLOR			, GDATA_USAGE_SUBSYS_VIDEO	|  5			);	// 0x20000005;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TANGENT				, GDATA_USAGE_SUBSYS_VIDEO	|  6			);	// 0x20000006;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BITANGENT			, GDATA_USAGE_SUBSYS_VIDEO	|  7			);	// 0x20000007;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BLENDWEIGHT			, GDATA_USAGE_SUBSYS_VIDEO	|  8			);	// 0x20000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BLENDINDICES		, GDATA_USAGE_SUBSYS_VIDEO	|  9			);	// 0x20000009;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TEXEL				, GDATA_USAGE_SUBSYS_VIDEO	| 10			);	// 0x20000010;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VOXEL				, GDATA_USAGE_SUBSYS_VIDEO	| 11			);	// 0x20000011;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ALPHA				, GDATA_USAGE_SUBSYS_VIDEO	| 12			);	// 0x20000012;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_HEIGHT				, GDATA_USAGE_SUBSYS_VIDEO	| 13			);	// 0x20000013;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_SCALE				, GDATA_USAGE_SUBSYS_VIDEO	| 14			);	// 0x20000014;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TRANSFORM			, GDATA_USAGE_SUBSYS_VIDEO	| 15			);	// 0x20000015;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DEPTH				, GDATA_USAGE_SUBSYS_VIDEO	| 16			);	// 0x20000016;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_STENCIL				, GDATA_USAGE_SUBSYS_VIDEO	| 17			);	// 0x20000017;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DEPTHSTENCIL		, GDATA_USAGE_SUBSYS_VIDEO	| 18			);	// 0x20000018;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_RENDERTARGET		, GDATA_USAGE_SUBSYS_VIDEO	| 19			);	// 0x20000019;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VERTEXSHADER		, GDATA_USAGE_SUBSYS_VIDEO	| 20			);	// 0x20000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_GEOMETRYSHADER		, GDATA_USAGE_SUBSYS_VIDEO	| 21			);	// 0x20000021;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_PIXELSHADER			, GDATA_USAGE_SUBSYS_VIDEO	| 22			);	// 0x20000022;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DOMAINSHADER		, GDATA_USAGE_SUBSYS_VIDEO	| 23			);	// 0x20000023;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_HULLSHADER			, GDATA_USAGE_SUBSYS_VIDEO	| 24			);	// 0x20000024;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_COMPUTESHADER		, GDATA_USAGE_SUBSYS_VIDEO	| 25			);	// 0x20000025;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_STREAMOUTPUT		, GDATA_USAGE_SUBSYS_VIDEO	| 26			);	// 0x20000026;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_UNORDEREDACCESS		, GDATA_USAGE_SUBSYS_VIDEO	| 27			);	// 0x20000027;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DECODER				, GDATA_USAGE_SUBSYS_VIDEO	| 28			);	// 0x20000028;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ENCODER				, GDATA_USAGE_SUBSYS_VIDEO	| 29			);	// 0x20000029;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_DIRECT				, GDATA_USAGE_SUBSYS_VIDEO	| 30			);	// 0x20000030;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_COMPUTE				, GDATA_USAGE_SUBSYS_VIDEO	| 31			);	// 0x20000031;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_COPY				, GDATA_USAGE_SUBSYS_VIDEO	| 32			);	// 0x20000032;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BUNDLE				, GDATA_USAGE_SUBSYS_VIDEO	| 33			);	// 0x20000033;

	// Audio usages 
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_WAVE				, GDATA_USAGE_SUBSYS_AUDIO	| ( 1 << 0 )	);	// 0x40000001;

	// Physics usages 
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ANGULARTENSOR		, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  0 )	);	// 0x80000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_POSITION			, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  1 )	);	// 0x80000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_VELOCITY			, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  2 )	);	// 0x80000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ROTATION			, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  3 )	);	// 0x80000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ACCELERATION		, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  4 )	);	// 0x80000010;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_SPEED				, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  5 )	);	// 0x80000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_ORIENTATION			, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  6 )	);	// 0x80000040;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_FORCE				, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  7 )	);	// 0x80000080;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_TRANSLATION			, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  8 )	);	// 0x80000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_BOUNDINGVOLUME		, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  9 )	);	// 0x80000200;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_PLANE				, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 << 10 )	);	// 0x80000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_RAY					, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 << 11 )	);	// 0x80000200;

	// ??
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_SYMBOL				, ( 1 << 0 )								);	// 0x1;

	struct STypeUsage {
		GDATA_TYPE	Type  ;
		GDATA_USAGE	Usage ;
	};

	#define GDATA_TYPE_TYPEUSAGE GDATA_TYPE_UINT32_2
}

#endif //__DATAUSAGE_H__928364092634829374234__
