#include "nwol_enum.h"

#ifndef __DATAUSAGE_H__928364092634829374234__
#define __DATAUSAGE_H__928364092634829374234__

namespace nwol
{
	// This is to let the api know how to deal with the data
	GDEFINE_ENUM_TYPE(GDATA_USAGE, uint32_t);
#define GDATA_TYPE_RESOURCEUSAGE	GDATA_TYPE_UINT32
	
	// 
	//GDEFINE_ENUM_VALUE(GDATA_USAGE, 0		, SUBSYS_NONE		);
	GDEFINE_ENUM_VALUE(GDATA_USAGE, 1<<28	, SUBSYS_CORE		);
	GDEFINE_ENUM_VALUE(GDATA_USAGE, 1<<29	, SUBSYS_VIDEO		);
	GDEFINE_ENUM_VALUE(GDATA_USAGE, 1<<30	, SUBSYS_AUDIO		);
	GDEFINE_ENUM_VALUE(GDATA_USAGE, 1<<31	, SUBSYS_PHYSICS	);

	// Base usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, 0											, GUSAGE_UNKNOWN			);
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 0  )	, GUSAGE_BINARY				);	// 0x10000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 1  )	, GUSAGE_TEXT				);	// 0x10000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 2  )	, GUSAGE_POINTER			);	// 0x10000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 3  )	, GUSAGE_DATATYPE			);	// 0x10000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 4  )	, GUSAGE_BEGIN				);	// 0x10000010;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 5  )	, GUSAGE_END				);	// 0x10000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 6  )	, GUSAGE_USAGE				);	// 0x10000040;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 7  )	, GUSAGE_NUMERIC			);	// 0x10000080;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 8  )	, GUSAGE_POD				);	// 0x10000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 9  )	, GUSAGE_CLASS				);	// 0x10000200;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_CORE	| ( 1 << 10 )	, GUSAGE_SCANCODE			);	// 0x10000400;

	// Derived base usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				| ( 1 << 11 )	, GUSAGE_SCALAR				);	// 0x10000800;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				| ( 1 << 12 )	, GUSAGE_VECTOR				);	// 0x10001000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				| ( 1 << 13 )	, GUSAGE_BOOLEAN			);	// 0x10002000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				| ( 1 << 14 )	, GUSAGE_RANGE				);	// 0x10004000;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GUSAGE_NUMERIC				| ( 1 << 15 )	, GUSAGE_MAP				);	// 0x10004000;

	// Video usages
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  1			, GUSAGE_INDEX				);	// 0x20000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  2			, GUSAGE_VERTEX				);	// 0x20000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  3			, GUSAGE_NORMAL				);	// 0x20000003;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  4			, GUSAGE_TEXCOORD			);	// 0x20000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  5			, GUSAGE_VERTEXCOLOR		);	// 0x20000005;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  6			, GUSAGE_TANGENT			);	// 0x20000006;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  7			, GUSAGE_BITANGENT			);	// 0x20000007;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  8			, GUSAGE_BLENDWEIGHT		);	// 0x20000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	|  9			, GUSAGE_BLENDINDICES		);	// 0x20000009;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 10			, GUSAGE_TEXEL				);	// 0x20000010;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 11			, GUSAGE_VOXEL				);	// 0x20000011;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 12			, GUSAGE_ALPHA				);	// 0x20000012;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 13			, GUSAGE_HEIGHT				);	// 0x20000013;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 14			, GUSAGE_SCALE				);	// 0x20000014;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 15			, GUSAGE_TRANSFORM			);	// 0x20000015;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 16			, GUSAGE_DEPTH				);	// 0x20000016;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 17			, GUSAGE_STENCIL			);	// 0x20000017;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 18			, GUSAGE_DEPTHSTENCIL		);	// 0x20000018;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 19			, GUSAGE_RENDERTARGET		);	// 0x20000019;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 20			, GUSAGE_VERTEXSHADER		);	// 0x20000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 21			, GUSAGE_GEOMETRYSHADER		);	// 0x20000021;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 22			, GUSAGE_PIXELSHADER		);	// 0x20000022;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 23			, GUSAGE_DOMAINSHADER		);	// 0x20000023;	
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 24			, GUSAGE_HULLSHADER			);	// 0x20000024;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 25			, GUSAGE_COMPUTESHADER		);	// 0x20000025;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 26			, GUSAGE_STREAMOUTPUT		);	// 0x20000026;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 27			, GUSAGE_UNORDEREDACCESS	);	// 0x20000027;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 28			, GUSAGE_DECODER			);	// 0x20000028;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 29			, GUSAGE_ENCODER			);	// 0x20000029;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 30			, GUSAGE_DIRECT				);	// 0x20000030;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 31			, GUSAGE_COMPUTE			);	// 0x20000031;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 32			, GUSAGE_COPY				);	// 0x20000032;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_VIDEO	| 33			, GUSAGE_BUNDLE				);	// 0x20000033;

	// Audio usages 
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_AUDIO	| ( 1 << 0 )	, GUSAGE_WAVE				);	// 0x40000001;

	// Physics usages 
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  0 )	, GUSAGE_ANGULARTENSOR		);	// 0x80000001;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  1 )	, GUSAGE_POSITION			);	// 0x80000002;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  2 )	, GUSAGE_VELOCITY			);	// 0x80000004;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  3 )	, GUSAGE_ROTATION			);	// 0x80000008;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  4 )	, GUSAGE_ACCELERATION		);	// 0x80000010;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  5 )	, GUSAGE_SPEED				);	// 0x80000020;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  6 )	, GUSAGE_ORIENTATION		);	// 0x80000040;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  7 )	, GUSAGE_FORCE				);	// 0x80000080;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  8 )	, GUSAGE_TRANSLATION		);	// 0x80000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 <<  9 )	, GUSAGE_BOUNDINGVOLUME		);	// 0x80000200;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 << 10 )	, GUSAGE_PLANE				);	// 0x80000100;
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, GDATA_USAGE_SUBSYS_PHYSICS | ( 1 << 11 )	, GUSAGE_RAY				);	// 0x80000200;

	// ??
	GDEFINE_ENUM_VALUE_NOPREFIX(GDATA_USAGE, ( 1 << 0 )									, GUSAGE_SYMBOL				);	// 0x1;

	struct STypeUsage {
		GDATA_TYPE	Type  ;
		GDATA_USAGE	Usage ;
	};

	#define GDATA_TYPE_TYPEUSAGE GDATA_TYPE_UINT32_2
}

#endif //__DATAUSAGE_H__928364092634829374234__
